//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDG.Utility.Localization.SourceFiles {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FiiiCoinLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FiiiCoinLocalization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WDG.Utility.Localization.SourceFiles.FiiiCoinLocalization", typeof(FiiiCoinLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 UNKNOWN_ERROR 的本地化字符串。
        /// </summary>
        public static string _0000000 {
            get {
                return ResourceManager.GetString("0000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENGINE_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1000000 {
            get {
                return ResourceManager.GetString("1000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTXO_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1010000 {
            get {
                return ResourceManager.GetString("1010000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020000 {
            get {
                return ResourceManager.GetString("1020000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VERIFY_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020100 {
            get {
                return ResourceManager.GetString("1020100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_HASH_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020101 {
            get {
                return ResourceManager.GetString("1020101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_HAS_BEEN_EXISTED 的本地化字符串。
        /// </summary>
        public static string _1020102 {
            get {
                return ResourceManager.GetString("1020102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INPUT_AND_OUTPUT_CANNOT_BE_EMPTY 的本地化字符串。
        /// </summary>
        public static string _1020103 {
            get {
                return ResourceManager.GetString("1020103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INPUT_EXCEEDED_THE_LIMIT 的本地化字符串。
        /// </summary>
        public static string _1020104 {
            get {
                return ResourceManager.GetString("1020104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OUTPUT_EXCEEDED_THE_LIMIT 的本地化字符串。
        /// </summary>
        public static string _1020105 {
            get {
                return ResourceManager.GetString("1020105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HASH_CANNOT_BE_EMPTY 的本地化字符串。
        /// </summary>
        public static string _1020106 {
            get {
                return ResourceManager.GetString("1020106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOCK_TIME_EXCEEDED_THE_LIMIT 的本地化字符串。
        /// </summary>
        public static string _1020107 {
            get {
                return ResourceManager.GetString("1020107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_SIZE_BELOW_THE_LIMIT 的本地化字符串。
        /// </summary>
        public static string _1020108 {
            get {
                return ResourceManager.GetString("1020108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NUMBER_OF_SIGNATURES_EXCEEDED_THE_LIMIT 的本地化字符串。
        /// </summary>
        public static string _1020109 {
            get {
                return ResourceManager.GetString("1020109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SCRIPT_FORMAT_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020110 {
            get {
                return ResourceManager.GetString("1020110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTXO_HAS_BEEN_SPENT 的本地化字符串。
        /// </summary>
        public static string _1020111 {
            get {
                return ResourceManager.GetString("1020111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COINBASE_UTXO_LESS_THAN_100_CONFIRMS 的本地化字符串。
        /// </summary>
        public static string _1020112 {
            get {
                return ResourceManager.GetString("1020112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OUTPUT_LARGE_THAN_INPUT 的本地化字符串。
        /// </summary>
        public static string _1020113 {
            get {
                return ResourceManager.GetString("1020113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_FEE_IS_TOO_FEW 的本地化字符串。
        /// </summary>
        public static string _1020114 {
            get {
                return ResourceManager.GetString("1020114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTXO_UNLOCK_FAIL 的本地化字符串。
        /// </summary>
        public static string _1020115 {
            get {
                return ResourceManager.GetString("1020115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTXO_NOT_EXISTED 的本地化字符串。
        /// </summary>
        public static string _1020116 {
            get {
                return ResourceManager.GetString("1020116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COINBASE_FORMAT_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020117 {
            get {
                return ResourceManager.GetString("1020117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COINBASE_OUTPUT_AMOUNT_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020118 {
            get {
                return ResourceManager.GetString("1020118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRIVATE_KEY_IS_ERROR 的本地化字符串。
        /// </summary>
        public static string _1020119 {
            get {
                return ResourceManager.GetString("1020119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_IS_LOCKED 的本地化字符串。
        /// </summary>
        public static string _1020120 {
            get {
                return ResourceManager.GetString("1020120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COINBASE_NEED_100_CONFIRMS 的本地化字符串。
        /// </summary>
        public static string _1020121 {
            get {
                return ResourceManager.GetString("1020121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1030000 {
            get {
                return ResourceManager.GetString("1030000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_VERIFY_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1030100 {
            get {
                return ResourceManager.GetString("1030100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_HAS_BEEN_EXISTED 的本地化字符串。
        /// </summary>
        public static string _1030101 {
            get {
                return ResourceManager.GetString("1030101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_HASH_ERROR 的本地化字符串。
        /// </summary>
        public static string _1030102 {
            get {
                return ResourceManager.GetString("1030102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_SIZE_LARGE_THAN_LIMIT 的本地化字符串。
        /// </summary>
        public static string _1030103 {
            get {
                return ResourceManager.GetString("1030103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRANSACTION_VERIFY_FAIL 的本地化字符串。
        /// </summary>
        public static string _1030104 {
            get {
                return ResourceManager.GetString("1030104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POW_VERIFY_FAIL 的本地化字符串。
        /// </summary>
        public static string _1030105 {
            get {
                return ResourceManager.GetString("1030105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BITS_IS_WRONG 的本地化字符串。
        /// </summary>
        public static string _1030106 {
            get {
                return ResourceManager.GetString("1030106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PREV_BLOCK_NOT_EXISTED 的本地化字符串。
        /// </summary>
        public static string _1030107 {
            get {
                return ResourceManager.GetString("1030107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_TIME_IS_ERROR 的本地化字符串。
        /// </summary>
        public static string _1030108 {
            get {
                return ResourceManager.GetString("1030108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_CHAIN_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1040000 {
            get {
                return ResourceManager.GetString("1040000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENGINE_ACCOUNT_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1050000 {
            get {
                return ResourceManager.GetString("1050000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P2P_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1060000 {
            get {
                return ResourceManager.GetString("1060000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONNECTION_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1060100 {
            get {
                return ResourceManager.GetString("1060100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HOST_NAME_CAN_NOT_RESOLVED_TO_IP_ADDRESS 的本地化字符串。
        /// </summary>
        public static string _1060101 {
            get {
                return ResourceManager.GetString("1060101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THE_NUMBER_OF_CONNECTIONS_IS_FULL 的本地化字符串。
        /// </summary>
        public static string _1060102 {
            get {
                return ResourceManager.GetString("1060102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THE_PEER_IS_EXISTED 的本地化字符串。
        /// </summary>
        public static string _1060103 {
            get {
                return ResourceManager.GetString("1060103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NOT_RECEIVED_HEARTBEAT_MESSAGE_FOR_A_LONG_TIME 的本地化字符串。
        /// </summary>
        public static string _1060105 {
            get {
                return ResourceManager.GetString("1060105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P2P_VERSION_NOT_BE_SUPPORT_BY_REMOTE_PEER 的本地化字符串。
        /// </summary>
        public static string _1060106 {
            get {
                return ResourceManager.GetString("1060106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIME_NOT_MATCH_WITH_RMOTE_PEER 的本地化字符串。
        /// </summary>
        public static string _1060107 {
            get {
                return ResourceManager.GetString("1060107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEER_IN_BLACK_LIST 的本地化字符串。
        /// </summary>
        public static string _1060108 {
            get {
                return ResourceManager.GetString("1060108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLET_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1070000 {
            get {
                return ResourceManager.GetString("1070000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DECRYPT_DATA_ERROR 的本地化字符串。
        /// </summary>
        public static string _1070001 {
            get {
                return ResourceManager.GetString("1070001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DATA_SAVE_TO_FILE_ERROR 的本地化字符串。
        /// </summary>
        public static string _1070002 {
            get {
                return ResourceManager.GetString("1070002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHECK_PASSWORD_ERROR 的本地化字符串。
        /// </summary>
        public static string _1070003 {
            get {
                return ResourceManager.GetString("1070003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLET_IO_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1070100 {
            get {
                return ResourceManager.GetString("1070100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FILE_NOT_FOUND 的本地化字符串。
        /// </summary>
        public static string _1070101 {
            get {
                return ResourceManager.GetString("1070101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXTENSION_NAME_NOT_SUPPORT 的本地化字符串。
        /// </summary>
        public static string _1070102 {
            get {
                return ResourceManager.GetString("1070102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FILE_DATA_INVALID 的本地化字符串。
        /// </summary>
        public static string _1070103 {
            get {
                return ResourceManager.GetString("1070103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLET_DB_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _1080200 {
            get {
                return ResourceManager.GetString("1080200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXECUTE_SQL_ERROR 的本地化字符串。
        /// </summary>
        public static string _1080201 {
            get {
                return ResourceManager.GetString("1080201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOAD_DATA_ERROR 的本地化字符串。
        /// </summary>
        public static string _1080202 {
            get {
                return ResourceManager.GetString("1080202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SERVICE_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2000000 {
            get {
                return ResourceManager.GetString("2000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SERVICE_UTXO_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2010000 {
            get {
                return ResourceManager.GetString("2010000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN_NOT_ENCRYPT_AN_ENCRYPTED_WALLET 的本地化字符串。
        /// </summary>
        public static string _2010001 {
            get {
                return ResourceManager.GetString("2010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN_NOT_LOCK_AN_UNENCRYPTED_WALLET 的本地化字符串。
        /// </summary>
        public static string _2010002 {
            get {
                return ResourceManager.GetString("2010002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN_NOT_UNLOCK_AN_UNENCRYPTED_WALLET 的本地化字符串。
        /// </summary>
        public static string _2010003 {
            get {
                return ResourceManager.GetString("2010003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN_NOT_CHANGE_PASSWORD_IN_AN_UNENCRYPTED_WALLET 的本地化字符串。
        /// </summary>
        public static string _2010004 {
            get {
                return ResourceManager.GetString("2010004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLET_HAS_BEEN_LOCKED 的本地化字符串。
        /// </summary>
        public static string _2010005 {
            get {
                return ResourceManager.GetString("2010005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SERVICE_TRANSACTION_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2020000 {
            get {
                return ResourceManager.GetString("2020000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TO_ADDRESS_INVALID 的本地化字符串。
        /// </summary>
        public static string _2020001 {
            get {
                return ResourceManager.GetString("2020001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BALANCE_NOT_ENOUGH 的本地化字符串。
        /// </summary>
        public static string _2020002 {
            get {
                return ResourceManager.GetString("2020002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEND_AMOUNT_LESS_THAN_FEE 的本地化字符串。
        /// </summary>
        public static string _2020003 {
            get {
                return ResourceManager.GetString("2020003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEE_DEDUCT_ADDRESS_INVALID 的本地化字符串。
        /// </summary>
        public static string _2020004 {
            get {
                return ResourceManager.GetString("2020004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLET_DECRYPT_FAIL 的本地化字符串。
        /// </summary>
        public static string _2020005 {
            get {
                return ResourceManager.GetString("2020005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SERVICE_ACCOUNT_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2030000 {
            get {
                return ResourceManager.GetString("2030000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACCOUNT_NOT_FOUND 的本地化字符串。
        /// </summary>
        public static string _2030001 {
            get {
                return ResourceManager.GetString("2030001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEFAULT_ACCOUNT_NOT_SET 的本地化字符串。
        /// </summary>
        public static string _2030002 {
            get {
                return ResourceManager.GetString("2030002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADDRESS_BOOK_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2040000 {
            get {
                return ResourceManager.GetString("2040000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN_NOT_ADDED_SELF_ACCOUNT_INTO_ADDRESS_BOOK 的本地化字符串。
        /// </summary>
        public static string _2040001 {
            get {
                return ResourceManager.GetString("2040001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NETWORK_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2050000 {
            get {
                return ResourceManager.GetString("2050000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P2P_SERVICE_NOT_START 的本地化字符串。
        /// </summary>
        public static string _2050001 {
            get {
                return ResourceManager.GetString("2050001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NODE_EXISTED 的本地化字符串。
        /// </summary>
        public static string _2050002 {
            get {
                return ResourceManager.GetString("2050002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NODE_NOT_EXISTED 的本地化字符串。
        /// </summary>
        public static string _2050003 {
            get {
                return ResourceManager.GetString("2050003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NODE_IN_THE_BLACK_LIST 的本地化字符串。
        /// </summary>
        public static string _2050004 {
            get {
                return ResourceManager.GetString("2050004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NODE_ADDRESS_FORMAT_INVALID 的本地化字符串。
        /// </summary>
        public static string _2050005 {
            get {
                return ResourceManager.GetString("2050005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SET_BAN_COMMAND_PARAMETER_NOT_SUPPORTED 的本地化字符串。
        /// </summary>
        public static string _2050006 {
            get {
                return ResourceManager.GetString("2050006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_CHAIN_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2060000 {
            get {
                return ResourceManager.GetString("2060000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAME_HEIGHT_BLOCK_HAS_BEEN_GENERATED 的本地化字符串。
        /// </summary>
        public static string _2060001 {
            get {
                return ResourceManager.GetString("2060001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK_DESERIALIZE_FAILED 的本地化字符串。
        /// </summary>
        public static string _2060002 {
            get {
                return ResourceManager.GetString("2060002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SERVICE_WALLET_COMMON_ERROR 的本地化字符串。
        /// </summary>
        public static string _2070000 {
            get {
                return ResourceManager.GetString("2070000", resourceCulture);
            }
        }
    }
}
